#!/bin/sh

: "${MKOSI_INITRD:=/usr/bin/mkosi-initrd}"

if [ ! -x "$MKOSI_INITRD" ]; then
	echo "${0##*/}: mkosi-initrd is not installed, not rebuilding the initrd." >&2
	exit 0
fi

initrd_warn_chroot_build() {
	# FIXME: mkosi-initrd does not provide anything like --regenerate-all yet
	echo "Please regenerate all the initrds with \"$MKOSI_INITRD\" as soon as your system is complete." >&2
}

initrd_regenerate() {
	local kver="$1"
	"$MKOSI_INITRD" --kernel-version "$kver" -O "/boot" -o "initrd-$kver"
}

initrd_regenerate_all() {
	local d

	# FIXME: mkosi-initrd does not provide anything like --regenerate-all yet
	for d in /lib/modules/*; do
		[ -d "$d" ] || continue
		[ -f "$d/modules.dep" ] || [ -f "$d/modules.dep.bin" ] || continue
		kver=${d##*/}
		"$MKOSI_INITRD" --kernel-version "$kver" -O "/boot" -o "initrd-$kver" || return $?
	done
}
