#! /bin/sh
# Copyright (c) 2021-2025 SUSE LLC
# SPDX-License-Identifier: GPL-2.0-or-later

ME="${0##*/}"
if [ -e /etc/initrd-release ]; then
    [ "$RD_DEBUG" != "yes" ] || \
	echo "$ME: called in initramfs for \"$@\" - ignoring" >&2
    exit 0
fi

# Never unblacklist non-interactively
if ! tty -s <&0; then
    exit 0
fi

if [ $UID -ne 0 ]; then
    echo "$ME: you must be root to run this program" >&2
    exit 1
fi

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    echo "Usage: $ME module [config-basename]" >&2
    exit 1
fi

MODULE=$1

# Determine which vendor config file covers this module, and set CONF to
# the corresponding override path in /etc/modprobe.d/.
#
# Two calling conventions are supported:
#
#   unblacklist MODULE
#     Used by filesystem blacklists (60-blacklist_fs-MODULE.conf) and
#     non-filesystem blacklists that follow the 60-blacklist-MODULE.conf
#     naming convention.  The vendor file is located by pattern.
#
#   unblacklist MODULE CONFIG-BASENAME
#     Used when the vendor filename does not encode the module name
#     (e.g. 50-blacklist-rndis.conf for rndis_host).  The basename is
#     supplied explicitly by the install directive in the vendor file so
#     that the correct /etc/ override is created.
#
CONF=""
if [ -n "${2:-}" ]; then
    # Explicit config basename supplied by the install directive.
    # Validate that the referenced vendor file actually exists to guard
    # against typos in install directives.
    if [ -f "/usr/lib/modprobe.d/$2.conf" ]; then
        CONF="/etc/modprobe.d/$2.conf"
    else
        echo "$ME: vendor file /usr/lib/modprobe.d/$2.conf not found" >&2
        exit 1
    fi
elif [ -f "/usr/lib/modprobe.d/60-blacklist_fs-$MODULE.conf" ]; then
    CONF="/etc/modprobe.d/60-blacklist_fs-$MODULE.conf"
elif [ -f "/usr/lib/modprobe.d/60-blacklist-$MODULE.conf" ]; then
    CONF="/etc/modprobe.d/60-blacklist-$MODULE.conf"
else
    echo "$ME: Invalid or unknown module \"$MODULE\"" >&2
    exit 1
fi

if [ -L "$CONF" ]; then
    if [ x"$(readlink -f "$CONF")" = x/dev/null ]; then
	# already linked to /dev/null
	exit 0
    else
	echo "$ME: $CONF is in unexpected state, exiting" >&2
	exit 1
    fi
elif [ -f "$CONF" ]; then
    if ! grep -E -q "^[[:space:]]*blacklist[[:space:]]+$MODULE" "$CONF"; then
	# not blacklisted
	exit 0
    fi
    if ! grep -E -q '^# __THIS FILE MAY BE MODIFIED__' "$CONF"; then
	echo "$ME: $CONF exists, cannot modify it" >&2
	exit 1
    fi
elif [ -e "$CONF" ]; then
    echo "$ME: $CONF is in unexpected state, exiting" >&2
    exit 1
fi

echo "$ME: loading module $MODULE" >&2
_a=
while [ -z "$_a" ]; do
    echo -n "$ME: Do you want to un-blacklist $MODULE permanently (<y>es/<n>o/n<e>ver)? " >&2
    read _a
    case $_a in
	y|yes)   _a=yes;;
	n|no)    _a=no;;
	e|never) _a=never;;
	*)       _a=;;
    esac
done
case $_a in
    no)
	echo "$ME: not un-blacklisting $MODULE" >&2
	exit 0
	;;
    never)
	echo "$ME: creating $CONF" >&2
	rm -f "$CONF"
	cat >$CONF <<EOF
# created by $0 (user wants to never unblacklist this module)
blacklist $MODULE
EOF
	exit 0
	;;
esac

if ln -sf /dev/null "$CONF"; then
    echo "$ME: $MODULE un-blacklisted by creating $CONF" >&2
    exit 0
else
    echo "$ME: Failed to create $CONF" >&2
    exit 1
fi
